import type { Plugin } from 'vite';
import fs from 'fs';
import path from 'path';

interface PagesJson {
  pages?: Array<{
    path: string;
    [key: string]: any;
  }>;
  subPackages?: Array<{
    root: string;
    pages: Array<{
      path: string;
      [key: string]: any;
    }>;
  }>;
  [key: string]: any;
}

/**
 * 移除 JSON 中的注释（支持 JSONC 格式）
 */
function stripJsonComments(jsonString: string): string {
  let result = '';
  let inString = false;
  let inSingleLineComment = false;
  let inMultiLineComment = false;
  let escapeNext = false;

  for (let i = 0; i < jsonString.length; i++) {
    const char = jsonString[i];
    const nextChar = jsonString[i + 1];

    // 处理转义字符
    if (escapeNext) {
      if (inString) {
        result += char;
      }
      escapeNext = false;
      continue;
    }

    if (char === '\\' && inString) {
      result += char;
      escapeNext = true;
      continue;
    }

    // 处理字符串
    if (char === '"' && !inSingleLineComment && !inMultiLineComment) {
      inString = !inString;
      result += char;
      continue;
    }

    // 如果在字符串内，直接添加字符
    if (inString) {
      result += char;
      continue;
    }

    // 处理多行注释结束
    if (inMultiLineComment) {
      if (char === '*' && nextChar === '/') {
        inMultiLineComment = false;
        i++; // 跳过 '/'
      }
      continue;
    }

    // 处理单行注释结束
    if (inSingleLineComment) {
      if (char === '\n' || char === '\r') {
        inSingleLineComment = false;
        result += char; // 保留换行符
      }
      continue;
    }

    // 检测注释开始
    if (char === '/') {
      if (nextChar === '/') {
        inSingleLineComment = true;
        i++; // 跳过第二个 '/'
        continue;
      }
      if (nextChar === '*') {
        inMultiLineComment = true;
        i++; // 跳过 '*'
        continue;
      }
    }

    // 正常字符
    result += char;
  }

  return result;
}

/**
 * 从 pages.json 提取所有页面路径
 */
function extractPagePaths(pagesJson: PagesJson): string[] {
  const pagePaths: string[] = [];

  // 提取主包页面
  if (pagesJson.pages && Array.isArray(pagesJson.pages)) {
    pagesJson.pages.forEach((page) => {
      if (page.path) {
        pagePaths.push(page.path);
      }
    });
  }

  // 提取分包页面
  if (pagesJson.subPackages && Array.isArray(pagesJson.subPackages)) {
    pagesJson.subPackages.forEach((subPackage) => {
      const root = subPackage.root;
      if (subPackage.pages && Array.isArray(subPackage.pages)) {
        subPackage.pages.forEach((page) => {
          if (page.path) {
            const fullPath = `${root}/${page.path}`.replace(/\/+/g, '/');
            pagePaths.push(fullPath);
          }
        });
      }
    });
  }

  return pagePaths;
}

/**
 * 生成 TypeScript 代码
 */
function generateTypeScriptCode(pagePaths: string[]): string {
  const pagesArray = pagePaths.map((p) => `"${p}"`).join(', ');

  return `// Auto-generated by vite-plugin-pages-defined
// Do not edit this file manually

export const _Pages = [${pagesArray}] as const;
export type _PagePath = typeof _Pages[number];

type RouteFunction = (path: _PagePath, options?: { query?: Record<string, any>, json?: Record<string, any> }) => void;

interface ToRouteInterface {
  navigate: RouteFunction;
  redirect: RouteFunction;
  switchTab: RouteFunction;
  reLaunch: RouteFunction;
  back: (delta?: number) => void;
}

const buildUrl = (path: string, query?: Record<string, any>, json?: Record<string, any>): string => {
  const fullPath = path.startsWith('/') ? path : \`/\${path}\`;
  const params: string[] = [];

  if (query && Object.keys(query).length > 0) {
    Object.entries(query).forEach(([key, value]) => {
      params.push(\`\${encodeURIComponent(key)}=\${encodeURIComponent(String(value))}\`);
    });
  }

  if (json && Object.keys(json).length > 0) {
    const jsonStr = JSON.stringify(json);
    params.push(\`json=\${encodeURIComponent(jsonStr)}\`);
  }

  return params.length > 0 ? \`\${fullPath}?\${params.join('&')}\` : fullPath;
};

const ToRoute: ToRouteInterface = {
  navigate: (path, options) => {
    const url = buildUrl(path, options?.query, options?.json);
    uni.navigateTo({ url });
  },
  redirect: (path, options) => {
    const url = buildUrl(path, options?.query, options?.json);
    uni.redirectTo({ url });
  },
  switchTab: (path, options) => {
    const url = buildUrl(path, options?.query, options?.json);
    uni.switchTab({ url });
  },
  reLaunch: (path, options) => {
    const url = buildUrl(path, options?.query, options?.json);
    uni.reLaunch({ url });
  },
  back: (delta = 1) => {
    uni.navigateBack({ delta });
  }
};

export const _To = ToRoute;
`;
}

/**
 * 生成 pages.ts 文件
 */
function generatePagesFile(srcDir: string, outputPath: string): void {
  try {
    const pagesJsonPath = path.resolve(srcDir, 'pages.json');

    // 读取 pages.json
    if (!fs.existsSync(pagesJsonPath)) {
      console.warn('[pages-defined] pages.json not found');
      return;
    }

    const pagesJsonContent = fs.readFileSync(pagesJsonPath, 'utf-8');
    // 移除 JSON 注释后再解析
    const cleanedJson = stripJsonComments(pagesJsonContent);
    const pagesJson: PagesJson = JSON.parse(cleanedJson);

    // 提取所有页面路径
    const pagePaths = extractPagePaths(pagesJson);

    // 生成 TypeScript 代码
    const code = generateTypeScriptCode(pagePaths);

    // 确保输出目录存在
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // 写入文件
    fs.writeFileSync(outputPath, code, 'utf-8');
    console.log(`[pages-defined] Generated ${outputPath} with ${pagePaths.length} pages`);
  } catch (error) {
    console.error('[pages-defined] Error generating pages.ts:', error);
  }
}

/**
 * Vite 插件：从 pages.json 生成类型安全的路由定义
 */
export default function pagesDefinedPlugin(): Plugin {
  let srcDir: string;
  let outputPath: string;

  return {
    name: 'vite-plugin-pages-defined',

    configResolved(config) {
      // 确定 src 目录和输出路径
      srcDir = path.resolve(config.root, 'src');
      outputPath = path.resolve(srcDir, '.uniky/global/pages.ts');
    },

    buildStart() {
      // 在构建开始时生成 pages.ts
      generatePagesFile(srcDir, outputPath);
    },

    configureServer(server) {
      // 监听 pages.json 文件变化
      const pagesJsonPath = path.resolve(srcDir, 'pages.json');

      server.watcher.add(pagesJsonPath);
      server.watcher.on('change', (file) => {
        if (file === pagesJsonPath) {
          console.log('[pages-defined] pages.json changed, regenerating pages.ts...');
          generatePagesFile(srcDir, outputPath);
        }
      });

      // 初始生成
      generatePagesFile(srcDir, outputPath);
    }
  };
}
